# Generated by Django 3.2.5 on 2026-04-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=50, unique=True)),
                ('department_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manager_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ssn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycompany.department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycompany.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('project_number', models.IntegerField(primary_key=True, serialize=False)),
                ('project_location', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycompany.department')),
            ],
        ),
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.project')),
            ],
        ),
        migrations.CreateModel(
            name='DeptLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.department')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_name', models.CharField(max_length=100)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('birth_date', models.DateField()),
                ('relationship', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='mycompany.employee'),
        ),
        migrations.AddConstraint(
            model_name='workson',
            constraint=models.UniqueConstraint(fields=('employee', 'project'), name='unique_employee_project'),
        ),
        migrations.AddConstraint(
            model_name='deptlocation',
            constraint=models.UniqueConstraint(fields=('department', 'location'), name='unique_department_location'),
        ),
        migrations.AddConstraint(
            model_name='dependent',
            constraint=models.UniqueConstraint(fields=('employee', 'dependent_name'), name='unique_dependent'),
        ),
    ]
