# Generated by Django 3.2.5 on 2026-04-29 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptlocation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='mycompany.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='mycompany.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='mycompany.department'),
        ),
        migrations.AlterField(
            model_name='workson',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_on', to='mycompany.employee'),
        ),
        migrations.AlterField(
            model_name='workson',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workson',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_on', to='mycompany.project'),
        ),
    ]
