# Generated by Django 3.2.5 on 2026-04-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0002_auto_20260429_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
