# Generated by Django 6.0.4 on 2026-04-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dname", models.CharField(max_length=50)),
                ("dnumber", models.IntegerField(primary_key=True, serialize=False)),
                ("mgr_ssn", models.CharField(max_length=9)),
                ("mgr_start_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DeptLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dlocation", models.CharField(max_length=50)),
                (
                    "dnumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("fname", models.CharField(max_length=50)),
                ("minit", models.CharField(blank=True, max_length=1)),
                ("lname", models.CharField(max_length=50)),
                (
                    "ssn",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("bdate", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=1)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("super_ssn", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dependent_name", models.CharField(max_length=50)),
                ("sex", models.CharField(max_length=1)),
                ("bdate", models.DateField()),
                ("relationship", models.CharField(max_length=50)),
                (
                    "essn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("pname", models.CharField(max_length=50)),
                ("pnumber", models.IntegerField(primary_key=True, serialize=False)),
                ("plocation", models.CharField(max_length=50)),
                (
                    "dnum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorksOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "essn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.employee",
                    ),
                ),
                (
                    "pno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.project",
                    ),
                ),
            ],
        ),
    ]
